SET search_path = public;

DROP TABLE IF EXISTS reports CASCADE;
DROP TABLE IF EXISTS furniture_placements CASCADE;
DROP TABLE IF EXISTS favorites CASCADE;
DROP TABLE IF EXISTS chat_messages CASCADE;
DROP TABLE IF EXISTS chat_rooms CASCADE;
DROP TABLE IF EXISTS three_d_models CASCADE;
DROP TABLE IF EXISTS space_images CASCADE;
DROP TABLE IF EXISTS spaces CASCADE;
DROP TABLE IF EXISTS agent_profiles CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    social_type VARCHAR(20) CHECK (social_type IN ('GOOGLE', 'KAKAO')),
    google_email VARCHAR(100) UNIQUE,
    kakao_email VARCHAR(100) UNIQUE,
    name VARCHAR(50) NOT NULL,
    phone VARCHAR(30),
    role VARCHAR(20) NOT NULL DEFAULT 'USER' CHECK (role IN ('USER', 'ADMIN')),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ
);

CREATE TABLE agent_profiles (
    user_id BIGINT PRIMARY KEY,
    license_no VARCHAR(100) NOT NULL UNIQUE,
    verification_status VARCHAR(20) NOT NULL DEFAULT 'PENDING'
        CHECK (verification_status IN ('PENDING', 'APPROVED', 'REJECTED')),
    rejection_reason VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ,
    CONSTRAINT fk_agent_profiles_user
        FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE spaces (
    space_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id BIGINT NOT NULL,
    title VARCHAR(100) NOT NULL,
    address VARCHAR(255) NOT NULL,
    area DOUBLE PRECISION,
    deposit INTEGER,
    monthly_rent INTEGER,
    maintenance_fee INTEGER,
    room_type VARCHAR(50),
    available_date DATE,
    status VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE'
        CHECK (status IN ('AVAILABLE', 'RESERVED', 'DELETED')),
    living_environment_info TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ,
    CONSTRAINT fk_spaces_agent
        FOREIGN KEY (agent_id) REFERENCES users (user_id)
);

CREATE TABLE space_images (
    image_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    space_id BIGINT NOT NULL,
    image_order INTEGER NOT NULL,
    image_url VARCHAR(500) NOT NULL,
    CONSTRAINT fk_space_images_space
        FOREIGN KEY (space_id) REFERENCES spaces (space_id) ON DELETE CASCADE,
    CONSTRAINT uq_space_images_order UNIQUE (space_id, image_order)
);

CREATE TABLE three_d_models (
    model_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    space_id BIGINT NOT NULL,
    model_url VARCHAR(500) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ,
    CONSTRAINT fk_three_d_models_space
        FOREIGN KEY (space_id) REFERENCES spaces (space_id) ON DELETE CASCADE
);

CREATE TABLE chat_rooms (
    chat_room_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    space_id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ,
    CONSTRAINT fk_chat_rooms_space
        FOREIGN KEY (space_id) REFERENCES spaces (space_id),
    CONSTRAINT fk_chat_rooms_tenant
        FOREIGN KEY (tenant_id) REFERENCES users (user_id),
    CONSTRAINT uk_chat_rooms_space_tenant UNIQUE (space_id, tenant_id)
);

CREATE TABLE chat_messages (
    message_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_room_id BIGINT NOT NULL,
    sender_id BIGINT NOT NULL,
    message TEXT NOT NULL,
    sent_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_chat_messages_room
        FOREIGN KEY (chat_room_id) REFERENCES chat_rooms (chat_room_id) ON DELETE CASCADE,
    CONSTRAINT fk_chat_messages_sender
        FOREIGN KEY (sender_id) REFERENCES users (user_id)
);

CREATE TABLE favorites (
    favorite_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    space_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ,
    CONSTRAINT fk_favorites_user
        FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_favorites_space
        FOREIGN KEY (space_id) REFERENCES spaces (space_id) ON DELETE CASCADE,
    CONSTRAINT uk_favorites_user_space UNIQUE (user_id, space_id)
);

CREATE TABLE furniture_placements (
    placement_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    space_id BIGINT NOT NULL,
    layout_data JSONB,
    preview_image_url VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ,
    CONSTRAINT fk_furniture_placements_user
        FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_furniture_placements_space
        FOREIGN KEY (space_id) REFERENCES spaces (space_id) ON DELETE CASCADE
);

CREATE TABLE reports (
    report_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    space_id BIGINT NOT NULL,
    summary TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ,
    CONSTRAINT fk_reports_space
        FOREIGN KEY (space_id) REFERENCES spaces (space_id) ON DELETE CASCADE,
    CONSTRAINT uk_reports_space UNIQUE (space_id)
);

CREATE INDEX idx_spaces_status ON spaces (status);
CREATE INDEX idx_spaces_room_type ON spaces (room_type);
CREATE INDEX idx_spaces_deposit ON spaces (deposit);
CREATE INDEX idx_spaces_monthly_rent ON spaces (monthly_rent);
CREATE INDEX idx_chat_messages_room_sent_at ON chat_messages (chat_room_id, sent_at);
