SET search_path = public;

DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS reports CASCADE;

CREATE TABLE reports (
    report_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    space_id BIGINT NOT NULL,
    summary TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ,
    CONSTRAINT fk_reports_space
        FOREIGN KEY (space_id) REFERENCES spaces (space_id) ON DELETE CASCADE,
    CONSTRAINT uk_reports_space UNIQUE (space_id)
);

INSERT INTO reports (space_id, summary, created_at)
SELECT
    space_id,
    'Registration report generated when the space was created.',
    COALESCE(created_at, NOW())
FROM spaces
ON CONFLICT (space_id) DO NOTHING;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'uq_favorites_user_space'
            AND conrelid = 'favorites'::regclass
    ) THEN
        ALTER TABLE favorites RENAME CONSTRAINT uq_favorites_user_space TO uk_favorites_user_space;
    ELSIF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'uk_favorites_user_space'
            AND conrelid = 'favorites'::regclass
    ) THEN
        ALTER TABLE favorites
        ADD CONSTRAINT uk_favorites_user_space UNIQUE (user_id, space_id);
    END IF;
END $$;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'uq_chat_rooms_space_tenant'
            AND conrelid = 'chat_rooms'::regclass
    ) THEN
        ALTER TABLE chat_rooms RENAME CONSTRAINT uq_chat_rooms_space_tenant TO uk_chat_rooms_space_tenant;
    ELSIF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'uk_chat_rooms_space_tenant'
            AND conrelid = 'chat_rooms'::regclass
    ) THEN
        ALTER TABLE chat_rooms
        ADD CONSTRAINT uk_chat_rooms_space_tenant UNIQUE (space_id, tenant_id);
    END IF;
END $$;
